bind 0.0.0.0                
port 6379                   
protected-mode no           
tcp-keepalive 300

requirepass YOUR_REDIS_PASSWORD

rename-command FLUSHALL ""
rename-command FLUSHDB  ""
rename-command CONFIG   ""
rename-command KEYS     ""


dir C:/Redis/data            
dbfilename dump.rdb

save 900 1
save 300 10
save 60 10000

appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec


logfile "C:/Redis/logs/redis.log"   
loglevel notice


maxmemory 1gb
maxmemory-policy noeviction   
